# see https://docs.docker.com/compose/compose-file/ and
# https://docs.docker.com/compose/ in general.
# compose-internal networking uses container ports, not mapped host ports.

services:
  db34:
    # https://hub.docker.com/_/postgres
    image: postgres:14-bullseye
    restart: on-failure
    hostname: db
    ports:
      - "5034:5432"  # HOST:CONTAINER
    environment:
      POSTGRES_USER: ojs
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - "/srv/ojs/test/db/data:/var/lib/postgresql/data:rw"
  db33:
    # https://hub.docker.com/_/postgres
    image: postgres:14-bullseye
    restart: on-failure
    hostname: db
    ports:
      - "5033:5432"  # HOST:CONTAINER
    environment:
      POSTGRES_USER: ojs
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - "/srv/ojs33/test/db/data:/var/lib/postgresql/data:rw"
